name: 'dbt_ecommerce'
version: '1.0.0'
config-version: 2

# This profile name must match the one configured in ~/.dbt/profiles.yml file
profile: 'e-commerce-479214' 

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory to store compiled SQL and run artifacts
clean-targets:         # directories that are removed by `dbt clean`
  - "target"
  - "dbt_packages"

# -----------------------------------------------------------------------------
# Project Configuration Block
# Sets defaults for materialization and schemas for each model subdirectory.
# -----------------------------------------------------------------------------
models:
  dbt_ecommerce: # Matching the 'name' of project above
    
    # 1. Default Materialization
    +materialized: view 
    
    # 2. Staging Layer Configuration
    staging:
      thelook:
        +schema: staging_the_look 
        # Staging models are built as views for lower cost and storage
        +materialized: view 

    # 3. Intermediate Layer Configuration
    # Intermediate models are often set to tables for performance.
    intermediate:
      +schema: intermediate 
      # Set materialization to 'table' to optimize for speed in subsequent joins
      +materialized: table 

    # 4. Marts Layer Configuration
    # Final marts go into the production 'analytics' schema.
    marts:
      +schema: analytics # The schema your BI tools will connect to
      # Final marts are built as tables for fast BI query performance
      +materialized: table