version: 2

models:
  # ----------------------------------------------------
  # 1. Customer Dimension (dim_customers)
  # ----------------------------------------------------
  - name: dim_customers
    description: "The primary dimension table for customer analysis, containing lifetime value (LTV) and demographic information. Used for segmentation and cohort analysis."
    columns:
      - name: customer_key
        description: "The unique identifier for the customer (Foreign Key to Fact tables)."
        tests:
          - unique
          - not_null
      - name: email
        description: "Customer's email address."
        tests:
          - unique
      - name: country
        description: "The customer's country of residence."
      - name: traffic_source
        description: "The marketing channel that acquired the customer."
      - name: customer_cohort_month
        description: "The sign-up month (YYYY-MM), used for cohort retention tracking."
      - name: total_revenue_lifetime
        description: "Customer Lifetime Value (LTV)."
      - name: days_since_last_order
        description: "Recency metric (days since last purchase)."
      - name: customer_status_90_day
        description: "Categorical status: Active, Dormant, or New (No Orders)."
        
  # ----------------------------------------------------
  # 2. Product Dimension (dim_products)
  # ----------------------------------------------------
  - name: dim_products
    description: "The dimension table for product analysis, containing category, brand, and calculated average profitability metrics."
    columns:
      - name: product_key
        description: "The unique identifier for the product (Foreign Key to Fact tables)."
        tests:
          - unique
          - not_null
      - name: product_name
        description: "The name of the product."
      - name: product_brand
        description: "The brand of the product."
      - name: product_category
        description: "The primary category of the product."
      - name: retail_price
        description: "The average retail price of the product."
      - name: average_margin_percent
        description: "The calculated average gross profit margin percentage."

  # ----------------------------------------------------
  # 3. Sales Fact Table (fct_sales)
  # ----------------------------------------------------
  - name: fct_sales
    description: "The granular sales fact table. One row per order line item. Contains transaction metrics like revenue, cost, and profit."
    columns:
      - name: order_item_key
        description: "The primary key for the sales fact table (unique line item ID)."
        tests:
          - unique
          - not_null
      - name: customer_key
        description: "Foreign Key linking to dim_customers."
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_key
      - name: product_key
        description: "Foreign Key linking to dim_products."
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_key
      - name: transaction_at
        description: "The timestamp of the sales transaction."
        tests:
          - not_null
      - name: gross_revenue
        description: "The revenue (sale price) generated by this line item."
        tests:
          - dbt_expectations.expect_column_values_to_be_greater_than:
              value: 0
      - name: cost_of_goods_sold
        description: "The cost associated with this line item."
        tests:
          - not_null
      - name: gross_profit
        description: "Calculated margin: gross_revenue - cost_of_goods_sold."
      - name: is_returned
        description: "Boolean flag indicating if the item was returned."